"""empty message

Revision ID: 140ebc6f52bb
Revises: 
Create Date: 2021-10-07 23:25:13.002473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140ebc6f52bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('numberID', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vaccinated', sa.Boolean(), nullable=False),
    sa.Column('occupation', sa.String(length=30), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_init', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('age_start', sa.Integer(), nullable=False),
    sa.Column('age_end', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('user')
    # ### end Alembic commands ###
